# Generated by Django 4.2.6 on 2023-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='media', verbose_name='IMG'),
            preserve_default=False,
        ),
    ]
