# Generated by Django 4.2.6 on 2023-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=254, verbose_name='Collection info')),
                ('name', models.CharField(max_length=254, verbose_name='Collection name')),
                ('img', models.ImageField(upload_to='media', verbose_name='IMG')),
            ],
        ),
    ]
