# Generated by Django 4.2.6 on 2023-10-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Product Price')),
                ('data_time', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='TrandyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='main.product')),
            ],
        ),
    ]
