# Generated by Django 4.2.6 on 2023-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_img_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=254, verbose_name='About')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'StayUpdated',
                'verbose_name_plural': 'StayUpdated',
            },
        ),
    ]
