# Generated by Django 4.2.6 on 2023-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_stayupdated_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcuts', models.ManyToManyField(to='main.product')),
            ],
            options={
                'verbose_name': 'OurShop',
                'verbose_name_plural': 'OurShop',
            },
        ),
    ]
