# Generated by Django 4.2.6 on 2023-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ourshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourshop',
            name='prodcuts',
        ),
        migrations.AddField(
            model_name='ourshop',
            name='product',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
