# Generated by Django 4.2.6 on 2023-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'ShippingAddress', 'verbose_name_plural': 'ShippingAddresses'},
        ),
    ]
