# Generated by Django 4.2.6 on 2023-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to="media", verbose_name="Slider Image"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Slider Title"),
                ),
                (
                    "slogan",
                    models.CharField(max_length=100, verbose_name="Slider Slugan"),
                ),
            ],
            options={
                "verbose_name": "GeneralSlider",
                "verbose_name_plural": "GeneralSliders",
            },
        ),
    ]
